<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Osiris.App</RootNamespace>
    <AssemblyName>Osiris.App</AssemblyName>
    <Version>2.0.10.0</Version>
    <ApplicationIcon>App.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- net48 无内置 WinForms SDK 引用，需引用程序集包 -->
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Osiris.Core\Osiris.Core.csproj" />
    <ProjectReference Include="..\Osiris.Engine.Skia\Osiris.Engine.Skia.csproj" />
    <ProjectReference Include="..\Osiris.Settings\Osiris.Settings.csproj" />
  </ItemGroup>

</Project>
