<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageId>$(AssemblyName)</PackageId>

    <!-- 排除 publish 文件夹，不在 VS 中显示 -->
    <DefaultItemExcludes>$(DefaultItemExcludes);publish\**</DefaultItemExcludes>

    <StartupObject>fptp.Program</StartupObject>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\lang.zh-CN.json">
      <LogicalName>fptp.Resources.lang.zh-CN.json</LogicalName>
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\lang.en-US.json">
      <LogicalName>fptp.Resources.lang.en-US.json</LogicalName>
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="CHANGELOG.md;README.md;CONTRIBUTING.md;API.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="*.pdf;fptp.bat;register-path.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\donate.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Windows.Forms" />
    <Using Include="System.Drawing" />
  </ItemGroup>



</Project>