<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Osiris.Settings</RootNamespace>
    <AssemblyName>Osiris.Settings</AssemblyName>
    <Version>2.0.7.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Osiris.Core\Osiris.Core.csproj" />
    <!-- netstandard2.0 无内置 System.Text.Json -->
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
